name: React Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - '**.js'
      - '**.jsx'
      - 'public/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "Lint failed"

      - name: Build React app
        run: npm run build

      - name: Trigger Vercel Deploy
        run: curl -X POST ${{ secrets.VERCEL_HOOK_URL }}
